apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gcp-devops-app

  template:
    metadata:
      labels:
        app: gcp-devops-app

    spec:
      containers:
      - name: gcp-devops-container
        image: asia-south1-docker.pkg.dev/project-d479dbab-4622-4305-b61/my-repo/gcp-devops-app:latest

        ports:
        - containerPort: 80
